export const OKRConstanst ={
    //Lista de OKRS
    LIST_OKRS: "LIST_OKRS",
    LIST_OKRS_SUCCESS: "LIST_OKRS_SUCCESS",
    LIST_OKRS_FAILURE: "LIST_OKRS_FAILURE",

    //Lista de OKRs
    LIST_OKRS_ID:"LIST_OKRS_ID",
    LIST_OKRS_ID_SUCCESS:"LIST_OKRS_ID_SUCCESS",
    LIST_OKRS_ID_FAILURE:"LIST_OKRS_ID_FAILURE",
}